/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2023-02-24
******************************************************************************
*/

/* Includes */
#include <stddef.h>

#include "iwdg.h"
#include "sysclock_config.h"
#include "usart_config.h"
#include "utils.h"

/* Private typedef */
/* Private define  */
/* Private macro */
/* Private variables */
uint8_t usart1_rx_dma_buffer[USART1_RX_DMA_BUFFER_SIZE];
char usart2_rx_dma_buffer[USART2_RX_DMA_BUFFER_SIZE];

/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void) {
    /**
     *  IMPORTANT NOTE!
     *  See the <system_*.c> file and how/if the SystemInit() function updates
     *  SCB->VTOR register. Sometimes the symbol VECT_TAB_SRAM needs to be defined
     *  when building the project if code has been located to RAM and interrupts
     *  are used. Otherwise the interrupt table located in flash will be used.
     *  E.g.  SCB->VTOR = 0x20000000;
     */

    /* Configure the system clock to 32 MHz and update SystemCoreClock */
    SetSysClock();
    SystemCoreClockUpdate();

    /* TODO - Add your application code here */
    USART1_dma_init();
    USART2_dma_init();
    IWDG_init();

    RCC->AHBENR |= 1;       // GPIOA ABH bus clock ON. p154
    GPIOA->MODER |= 0x400;  // GPIOA pin 5 to output. p184
    GPIOA->ODR ^= 0x20;

    USART2_send_string("App started...\n\r");
    /* Infinite loop */
    while (1) {
        GPIOA->ODR ^= 0x20;
        IWDG_feed();
        delay_ms(3000);
    }
    return 0;
}
